// src/app/about/page.tsx
import React from 'react';
import type { Metadata } from 'next';
import Link from 'next/link';
import {
  ShieldCheck,
  Scale,
  Heart,
  TrendingDown,
  Lock,
  ArrowRight,
  CheckCircle2,
  Clock,
  Zap,
} from 'lucide-react';
import { BloombergUniversalHeader } from '@/components/bloomberg/BloombergUniversalHeader';

export const dynamic = 'force-dynamic';

export const metadata: Metadata = {
  title: 'About The Honest Terminal — The Anti-Casino Trading Platform | Bloomberg Professional',
  description:
    'The only trading platform that profits from you not losing money. Free forever. Faster than everything. We show you what the herd is doing — and what happens to herds.',
  openGraph: {
    title: 'About Bloomberg Professional — The Honest Terminal',
    description: '“The only trading platform that profits from you not losing money.” Zero ads. Zero affiliates.',
    images: ['/api/og/reality?period=30'],
  },
};

export default function AboutPage() {
  return (
    <div className="min-h-screen bg-[#000000] text-[#d1d4dc] font-mono selection:bg-[#ff8800]/30">
      {/* Bloomberg Universal Header */}
      <BloombergUniversalHeader
        activeMnemonic="ABOUT"
        subtitle="FOUNDING MANIFESTO // INDEPENDENT ARCHITECTURE"
      />

      {/* Main Container */}
      <main className="max-w-4xl mx-auto px-4 py-12 space-y-12">
        {/* Hero Section */}
        <div className="space-y-4">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-bull/10 border border-bull/25 text-xs text-bull font-mono font-bold">
            <ShieldCheck size={13} />
            <span>THE HONEST TERMINAL • FOUNDING MANIFESTO</span>
          </div>

          <h1 className="text-3xl sm:text-5xl font-black text-white tracking-tight leading-tight">
            The only trading platform that profits from you not losing money.
          </h1>

          <p className="text-lg text-muted leading-relaxed">
            Free forever. Faster than everything. We show you what the herd is doing — and what happens to herds.
          </p>
        </div>

        {/* Section 1: The Problem with the Industry */}
        <section className="bg-panel border border-subtle rounded-2xl p-6 sm:p-8 space-y-4">
          <h2 className="text-xl font-bold text-white tracking-tight">
            Why Retail Trading Platforms Are Designed Like Casinos
          </h2>
          <div className="space-y-3 text-sm text-zinc-300 leading-relaxed">
            <p>
              Nearly every broker, charting app, and trading influencer makes money through an unspoken conflict of interest:
            </p>
            <ul className="space-y-2 list-disc list-inside text-muted pl-2">
              <li>
                <strong className="text-white">Brokers profit from turnover:</strong> They encourage high-frequency overtrading and 50x–100x leverage so they can collect commissions and liquidation fees.
              </li>
              <li>
                <strong className="text-white">Affiliate kickbacks:</strong> "Educators" and signal-sellers get paid up to 40% of the trading fees—or even direct cuts of the losses—generated by the followers they funnel to offshore exchanges.
              </li>
              <li>
                <strong className="text-white">Highlight reels:</strong> Winning screenshots are photoshopped or cherry-picked; losses are silently erased from history.
              </li>
            </ul>
            <p className="pt-2 text-white font-medium">
              If an entire industry profits when you lose your money, the platform you use should never be on their payroll.
            </p>
          </div>
        </section>

        {/* Section 2: How Celsius Works */}
        <section className="bg-panel border border-subtle rounded-2xl p-6 sm:p-8 space-y-5">
          <h2 className="text-xl font-bold text-white tracking-tight">
            How Celsius Works: Radically Lean, Funded by Trust
          </h2>
          <div className="space-y-4 text-sm text-zinc-300 leading-relaxed">
            <p>
              Celsius operates on an architectural principle of absolute leanness. Our entire platform costs just <strong className="text-bull">$150.00 per month</strong> to host on global edge servers. We don't have bloated sales departments, venture debt, or casino broker partnerships.
            </p>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 pt-2">
              <div className="p-4 rounded-xl bg-surface border border-subtle space-y-1.5">
                <span className="text-xs font-mono font-bold text-bull uppercase">Revenue Source 1: Micro-Donations</span>
                <p className="text-xs text-muted">
                  Traders who appreciate honest tools chip in $3–$5 per month on our public <Link href="/funding" className="text-bull underline">/funding</Link> page.
                </p>
              </div>

              <div className="p-4 rounded-xl bg-surface border border-subtle space-y-1.5">
                <span className="text-xs font-mono font-bold text-primary uppercase">Revenue Source 2: The Sentiment API</span>
                <p className="text-xs text-muted">
                  Quant desks and algorithmic traders pay $49/mo for real-time streaming sentiment feeds via our <Link href="/developers" className="text-primary underline">Developer API</Link>.
                </p>
              </div>
            </div>

            <p className="text-xs text-faint">
              That’s it. No advertisements. No affiliate links to unregulated casinos. Ever.
            </p>
          </div>
        </section>

        {/* Section 3: The Permanent Invariants */}
        <section className="space-y-4">
          <h2 className="text-xl font-bold text-white tracking-tight">
            The Permanent Invariants (Our Unbreakable Rules)
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="p-5 rounded-xl bg-panel border border-subtle space-y-2">
              <div className="flex items-center gap-2 font-bold text-white text-sm">
                <CheckCircle2 size={16} className="text-bull shrink-0" />
                <span>Context Everywhere</span>
              </div>
              <p className="text-xs text-muted leading-relaxed">
                No result is ever displayed without its drawdown, sample size, and BTC Buy-and-Hold benchmark comparison over the identical time window.
              </p>
            </div>

            <div className="p-5 rounded-xl bg-panel border border-subtle space-y-2">
              <div className="flex items-center gap-2 font-bold text-white text-sm">
                <CheckCircle2 size={16} className="text-bull shrink-0" />
                <span>Computed at Render Time</span>
              </div>
              <p className="text-xs text-muted leading-relaxed">
                Every percentage, statistic, and metric shown across the site is computed dynamically from the server ledger—never hardcoded or handwritten.
              </p>
            </div>

            <div className="p-5 rounded-xl bg-panel border border-subtle space-y-2">
              <div className="flex items-center gap-2 font-bold text-white text-sm">
                <CheckCircle2 size={16} className="text-bull shrink-0" />
                <span>Equal Billing for Losses</span>
              </div>
              <p className="text-xs text-muted leading-relaxed">
                Losses receive identical typographic prominence and dignity as wins across all share cards and journal entries. A disciplined loss is a badge of honor.
              </p>
            </div>

            <div className="p-5 rounded-xl bg-panel border border-subtle space-y-2">
              <div className="flex items-center gap-2 font-bold text-white text-sm">
                <CheckCircle2 size={16} className="text-bull shrink-0" />
                <span>Cryptographic Proofs</span>
              </div>
              <p className="text-xs text-muted leading-relaxed">
                All trade histories are hash-chained. Daily root hashes are cryptographically sealed at 00:00 UTC and published publicly on <Link href="/transparency" className="text-bull underline">/transparency</Link>.
              </p>
            </div>
          </div>
        </section>

        {/* CTA Footer */}
        <div className="p-6 rounded-2xl bg-gradient-to-r from-panel via-surface to-panel border border-subtle flex flex-col sm:flex-row items-center justify-between gap-4">
          <div>
            <h3 className="text-base font-bold text-white">Ready to trade with discipline?</h3>
            <p className="text-xs text-muted">Test your edge against reality without casino noise.</p>
          </div>
          <Link href="/" className="btn btn-primary px-5 py-2.5 rounded-lg text-xs font-bold flex items-center gap-1.5 shrink-0">
            <span>Launch The Terminal</span>
            <ArrowRight size={14} />
          </Link>
        </div>
      </main>
    </div>
  );
}
